# Markdownlint configuration file
default: true

# MD013/line-length - Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements:
    - br
    - summary
    - details

# MD041/first-line-heading - First line in file should be a top level heading
MD041: false
